[package]
name = "wdf-umdf-sys"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
paste = "1.0.15"
bytemuck = "1.16.1"
thiserror = "1.0.61"

[build-dependencies]
bindgen = "0.69.4"
thiserror = "1.0.61"
winreg = "0.52.0"
