[package]
name = "wdf-umdf-sys"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
paste = "1.0.14"
bytemuck = "1.14.3"
thiserror = "1.0.56"

[build-dependencies]
bindgen = "0.69.4"
thiserror = "1.0.56"
winreg = "0.52.0"
