[env.dev]
TARGET_PATH = "debug"

[env.prod]
TARGET_PATH = "release"

[tasks.set-build-path]
env = { "BUILD_TARGET_PATH" = { script = ['''
    for /f "tokens=*" %%a in ('cargo target-dir') do set target_dir=%%a

    echo %target_dir%\%TARGET_PATH%
'''] } }

[tasks.copy]
dependencies = ["set-build-path"]
script = [
    '''
    if not exist "..\\target\\output" (
        echo Directory not found, creating it...
        mkdir ..\\target\\output
    )
    ''',
    # copy output files to it
    '''
        copy %BUILD_TARGET_PATH%\*.exe ..\target\output
    ''',
]
